---
title: "R PLots using Viridis Color Map"
author: "Francis Kurian"
date: "9/25/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Simple Scatter Plot with distinct color trees

```{r orange}
library(viridis)
Orange$Tree <- factor(Orange$Tree, levels=seq(1,nlevels(Orange$Tree)),ordered=T)
tree.colors <- viridis(nlevels(Orange$Tree))

plot(x=Orange$age,y=Orange$circumference, 
     type ='p',pch=19,
     col=tree.colors[Orange$Tree], xlab='Age (days)', ylab='Circumference (mm)')
legend('topleft',legend=levels(Orange$Tree),col=tree.colors,pch=19)

```

# Generic Line Plot using Viridis Color Maps
## vector driven color and shape based on Orange$Tree field. 
```{r ggplot}
#library(viridis)
#Orange$Tree <- factor(Orange$Tree, levels=seq(1,nlevels(Orange$Tree)),ordered=T)
#tree.colors <- viridis(nlevels(Orange$Tree))

tree.shapes <- as.numeric(levels(Orange$Tree))

plot(Orange$age,Orange$circumference,type='n',main = "Trees:Growth by Age", 
     xlim = range(Orange$age), ylim = range(Orange$circumference), 
     xlab='Age (days)', ylab='Circumference (mm)')

for (i in tree.shapes) {
  newdata <- subset(Orange, Tree==i)
  lines(x=newdata$age,y=newdata$circumference, type ='o',pch=tree.shapes[i], col=tree.colors[i])
}

legend('topleft',legend=levels(Orange$Tree),col=tree.colors,pch=tree.shapes)


```
